alias: TechEnClair Automations
description: Exemples d’automations
mode: parallel
max: 10
sequence:
  - choose:
      - conditions:
          - condition: trigger
            id: arrivee
        sequence:
          - service: light.turn_on
            target: {entity_id: light.salon}
          - service: notify.mobile_app_tech
            data: {message: "Bienvenue à la maison"}
    default: []
trigger:
  - platform: state
    id: arrivee
    entity_id: person.tech
    to: home
